from __future__ import annotations

from datetime import datetime, timezone

from sliger.provenance import format_provenance


def test_format_provenance_includes_timestamp() -> None:
    stamp = datetime(2024, 6, 1, 12, 30, tzinfo=timezone.utc)
    text = format_provenance(generated_at=stamp)
    assert text == "Generated by sliger at 2024-06-01 12:30 UTC"


def test_format_provenance_includes_extra_keys() -> None:
    stamp = datetime(2024, 6, 1, 12, 30, tzinfo=timezone.utc)
    text = format_provenance(generated_at=stamp, extra={"deck": "Q1", "user": "ada"})
    assert "Generated by sliger at 2024-06-01 12:30 UTC" in text
    assert "deck: Q1" in text
    assert "user: ada" in text


def test_format_provenance_default_timestamp() -> None:
    text = format_provenance()
    assert text.startswith("Generated by sliger at ")
    assert text.endswith("UTC")
