from __future__ import annotations

import pytest

from sliger.templates import (
    FORMULA_PREFIX,
    alt_text_update_request,
    formula_from_element,
    looks_like_formula,
    notes_shape_id,
    speaker_notes_insert_requests,
)


def test_formula_from_element_uses_visible_text() -> None:
    element = {"objectId": "s1"}
    assert formula_from_element(element, "{{ name }}") == "{{ name }}"


def test_formula_from_element_prefers_stored_alt_text() -> None:
    element = {"objectId": "s1", "description": FORMULA_PREFIX + "{{ stored }}"}
    assert formula_from_element(element, "visible") == "{{ stored }}"


def test_formula_from_element_ignores_unprefixed_description() -> None:
    element = {"description": "speaker notes"}
    assert formula_from_element(element, "{{ name }}") == "{{ name }}"


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("{{ name }}", True),
        ("{% if ready %}go{% endif %}", True),
        ("  {{ x }}  ", True),
        ("plain text", False),
        ("{ not jinja }", False),
    ],
)
def test_looks_like_formula(text: str, expected: bool) -> None:
    assert looks_like_formula(text) is expected


def test_alt_text_update_request() -> None:
    request = alt_text_update_request("shape-1", "{{ name }}")
    assert request == {
        "updatePageElementAltText": {
            "objectId": "shape-1",
            "description": "sliger:{{ name }}",
        }
    }


def test_notes_shape_id_body_placeholder() -> None:
    slide = {
        "slideProperties": {
            "notesPage": {
                "pageElements": [
                    {
                        "objectId": "notes-body",
                        "shape": {
                            "shapeType": "TEXT_BOX",
                            "placeholder": {"type": "BODY"},
                        },
                    }
                ]
            }
        }
    }
    assert notes_shape_id(slide) == "notes-body"


def test_notes_shape_id_text_box_without_placeholder() -> None:
    slide = {
        "slideProperties": {
            "notesPage": {
                "pageElements": [
                    {"objectId": "notes-box", "shape": {"shapeType": "TEXT_BOX"}},
                ]
            }
        }
    }
    assert notes_shape_id(slide) == "notes-box"


def test_notes_shape_id_missing() -> None:
    assert notes_shape_id({}) is None
    assert notes_shape_id({"slideProperties": {}}) is None


def test_speaker_notes_insert_requests() -> None:
    assert speaker_notes_insert_requests("notes-1", "Generated by sliger") == [
        {"deleteText": {"objectId": "notes-1", "textRange": {"type": "ALL"}}},
        {
            "insertText": {
                "objectId": "notes-1",
                "insertionIndex": 0,
                "text": "Generated by sliger",
            }
        },
    ]


def test_speaker_notes_insert_requests_empty() -> None:
    assert speaker_notes_insert_requests("", "text") == []
    assert speaker_notes_insert_requests("notes-1", "") == []


def test_speaker_notes_insert_requests_without_replace() -> None:
    assert speaker_notes_insert_requests("notes-1", "Generated by sliger", replace=False) == [
        {
            "insertText": {
                "objectId": "notes-1",
                "insertionIndex": 0,
                "text": "Generated by sliger",
            }
        },
    ]
