"""Provenance blurb written into speaker notes after a render."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def format_provenance(
    *,
    generated_at: datetime | None = None,
    extra: dict[str, Any] | None = None,
) -> str:
    stamp = (generated_at or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M UTC")
    lines = [f"Generated by sliger at {stamp}"]
    if extra:
        for key, value in extra.items():
            lines.append(f"{key}: {value}")
    return "\n".join(lines)
